python main.py \
--obj_path data/source_meshes/car_face5000.obj \
--output_dir results/demo/car/wood1 \
--prompt a car made of wood  \
--normal_nerf_pe_numfreq 10  \
--init_r_and_s \
--init_roughness 0.5 \
--width 512 \
--local_percentage 0.7 \
--background 'black' \
--radius 2  \
--n_views 1 \
--material_nerf_pe_numfreq 12 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1  \
--frontview_std 12 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.01 \
--maxcrop 0.05 \
--seed 150 \
--n_iter 301 \
--learning_rate 0.0005 \
--frontview_center 1.96349 0.6283
